# Generated by Django 5.2.4 on 2025-07-26 20:11

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('dados', models.TextField()),
                ('hash_anterior', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('timestamp', models.FloatField(default=time.time)),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
